### PR TITLE
M_state_assign updated

### PR DESCRIPTION
**Pull request by AlexTryjan**
get_exp_last was added for third item in expression for M_value_math
various spelling changes (_heckles bentley_)

### CODE REVIEW

**Comment by mtbentley** [comment]
Looks good, but probably needs to take into account side effects inside the math expression

**Comment by mtbentley** [comment]
Well, that would actually be handle by M_state_math

But this needs to take the state as well, and probably just call M_value on the operands (since then can take anything that produces a number).

**Comment by mtbentley** [comment]
Also, you can reduce code duplication by doing something like

``` scheme
(define get_operator
  (lambda (o)
    (cond
      ((eq? '+ o) +)
      ((eq? '- o) -)
      ((eq? '* o) *)
      ((eq? '/ o) quotient)
      ((eq? '% o) remainder)
      (else o))))
```

And then do something like `((get_operator (get_first expression)) (get_second expression) (get_third expression)`.

**Comment by mtbentley** [comment]
Just to expand on my second comment, the code should be able to handle 

``` scheme
(+ (= x 10) (= y 20))
```

where `(= x 10)` resolves to 10, and `(= x 20)` resolves to 20

**Comment by mtbentley** [comment]
Also, rather than using `get_vars` and `get_values`, define `get_operator`, `get_operand1`, and `get_operand2`.

**Comment by DLance96** [comment]
Literally the worst pull request

**Pull request merged**
